name: Lint Plugin

on:
  push:
    paths: ["lua/**", "README.md", "docs/**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v11

      - name: Install Luacheck
        run: luarocks install luacheck

      - name: Lint Lua
        run: luacheck lua

      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: '**/*.md'

