name: Lint Plugin

on:
  push:
    paths: ["lua/**", "README.md", "docs/**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Lua
        uses: lunarmodules/luacheck-action@v1
        with:
          args: lua
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: '**/*.md'

